# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BukuS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('nama_penulis', models.CharField(max_length=200)),
                ('penyumbang', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'polls_BukuS',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('NIM', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'polls_Mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('NIM', models.CharField(max_length=200)),
                ('judul', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=200)),
                ('tanggal_pinjam', models.DateTimeField(blank=True, null=True)),
                ('tanggal_kembali', models.DateTimeField(blank=True, null=True)),
                ('tanggal_kembali_riil', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polls_Peminjaman',
            },
        ),
        migrations.CreateModel(
            name='Penyerahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_abstrak', models.BooleanField()),
                ('s_cd', models.BooleanField()),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BukuS')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Mahasiswa')),
            ],
            options={
                'db_table': 'polls_Penyerahan',
            },
        ),
        migrations.CreateModel(
            name='Skripsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_IND', models.CharField(max_length=200)),
                ('judul_ENG', models.CharField(max_length=200)),
                ('nama_penulis', models.CharField(max_length=200)),
                ('NIM', models.CharField(max_length=200)),
                ('pembimbing', models.CharField(max_length=200)),
                ('penguji', models.CharField(max_length=200)),
                ('tanggal_lulus', models.DateTimeField(blank=True, null=True)),
                ('tanggal_penyerahan', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polls_Skripsi',
            },
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_IND', models.CharField(max_length=200)),
                ('judul_ENG', models.CharField(max_length=200)),
                ('ps', models.CharField(max_length=50)),
                ('nama_penulis', models.CharField(max_length=200)),
                ('NIM', models.CharField(max_length=200)),
                ('pembimbing', models.CharField(max_length=200)),
                ('penguji', models.CharField(max_length=200)),
                ('tanggal_lulus', models.DateTimeField(blank=True, null=True)),
                ('tanggal_penyerahan', models.DateTimeField(blank=True, null=True)),
                ('no_panggil', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'polls_Tesis',
            },
        ),
    ]
