# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukus',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 10, 47, 9, 120838, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='bukus',
            name='pub_date',
            field=models.IntegerField(default=1945),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 10, 47, 9, 120838, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='skripsi',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 10, 47, 9, 120838, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tesis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 10, 47, 9, 120838, tzinfo=utc)),
        ),
    ]
