# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171211_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyerahan',
            name='mahasiswa',
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penyerahan',
            name='NIM',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='bukus',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 7, 11, 24, 686675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 7, 11, 24, 686675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='penyerahan',
            name='buku',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='skripsi',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 7, 11, 24, 686675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 7, 11, 24, 686675, tzinfo=utc)),
        ),
    ]
