# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171213_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukus',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 8, 16, 3, 252500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 8, 16, 3, 252500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='skripsi',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 8, 16, 3, 252500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 8, 16, 3, 252500, tzinfo=utc)),
        ),
    ]
